name: Docker Lint

on:
  workflow_call:
    inputs:
      dockerfilePath:
        description: "Dockerfile path"
        type: string
        default: Dockerfile

jobs:
  docker_lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Linting
        run: |
          docker run --rm -i ghcr.io/hadolint/hadolint:latest < ${{ inputs.dockerfilePath }}
