name: Docker Vulnerability Scan

on:
  workflow_call:
    inputs:
      dockerImage:
        description: "Docker Image name"
        type: string
        default: temp
      dockerfileDir:
        description: "Dockerfile dir"
        type: string
        default: ./
      policyPath:
        description: "Snyk file"
        type: string
        default: ./.snyk
    secrets:
      SNYK_TOKEN:
        description: "Snyk token to check vulnerabilities"
        required: true

jobs:
  docker_vulnerability_scan:
    name: Docker Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Test
        run: |
          cd ${{ inputs.dockerfileDir }} && \
          docker build -t ${{ inputs.dockerImage }} .
      - name: Vulnerabilities check
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ inputs.dockerImage }}
          args: --policy-path=${{ inputs.policyPath }}
