name: Terraform Deploy

on:
  workflow_call:
    inputs:
      modulePath:
        description: "Module path to run terraform commands"
        type: string
        default: ./
      awsRole:
        description: "The role to assume for the deployment"
        required: true
        type: string
      awsRegion:
        description: "The region for the deployment"
        required: true
        type: string
      awsSessionName:
        description: "The session name for the deployment"
        required: true
        type: string

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ inputs.awsRole }}
          role-session-name: ${{ inputs.awsSessionName }}
          aws-region: ${{ inputs.awsRegion }}
      - name: Terraform Init
        run: make -C ${{ inputs.modulePath }} init
      - name: Terraform Plan
        run: make -C ${{ inputs.modulePath }} plan
      - name: Terraform Apply
        run: make -C ${{ inputs.modulePath }} apply
